# Generated by Django 5.2.6 on 2025-09-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_customuser_documento_identidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('shampoo', 'Shampoo'), ('cera', 'Cera'), ('silicona', 'Silicona'), ('partes_negras', 'Protección de Partes Negras'), ('cuidado_pintura', 'Cuidado de Pintura')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLavado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.TextField(blank=True, help_text='Describe la experiencia del empleado.')),
                ('calificacion', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('disponible', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'rol': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='empleado_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('empleado_asignado', models.ForeignKey(limit_choices_to={'rol': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavados_asignados', to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(blank=True, to='reservations.producto')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehiculo')),
                ('tipo_lavado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.tipolavado')),
            ],
        ),
    ]
