# Generated by Django 5.2.6 on 2025-09-18 14:21

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    # Tipos de Lavado
    TipoLavado = apps.get_model('reservations', 'TipoLavado')
    TipoLavado.objects.bulk_create([
        TipoLavado(nombre='Lavado Rápido', precio=15000),
        TipoLavado(nombre='Lavado Profundo', precio=22000),
        TipoLavado(nombre='Lavado Premium', precio=30800),
        TipoLavado(nombre='Extrapremium', precio=40800),
    ])

    # Productos
    Producto = apps.get_model('reservations', 'Producto')
    Producto.objects.bulk_create([
        # Shampoos
        Producto(nombre='Brillo Intenso', categoria='shampoo'),
        Producto(nombre='Espuma Activa Pro', categoria='shampoo'),
        Producto(nombre='Limpieza Profunda pH Neutro', categoria='shampoo'),
        # Ceras
        Producto(nombre='Cera Carnauba Gold', categoria='cera'),
        Producto(nombre='Sellador Sintético Hydro-Seal', categoria='cera'),
        # Siliconas
        Producto(nombre='Silicona Premium Satinada', categoria='silicona'),
        Producto(nombre='Restaurador de Plásticos UV', categoria='silicona'),
        # Partes Negras
        Producto(nombre='Tinte para Llantas Negro Intenso', categoria='partes_negras'),
        Producto(nombre='Gel Protector de Gomas y Plásticos', categoria='partes_negras'),
        # Cuidado Pintura
        Producto(nombre='Descontaminante Férrico', categoria='cuidado_pintura'),
        Producto(nombre='Pulimento Fino 3 en 1', categoria='cuidado_pintura'),
        Producto(nombre='Glaze Abrillantador Espejo', categoria='cuidado_pintura'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
