# Generated by Django 5.2.5 on 2025-09-18 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_hora_cita',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='reservations.sede'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.sede'),
        ),
    ]
