# Generated by Django 5.2.5 on 2025-09-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_sede_remove_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_hora_cita',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.sede'),
        ),
    ]
