# Generated by Django 5.2.5

from django.db import migrations

def populate_sedes(apps, schema_editor):
    Sede = apps.get_model('reservations', 'Sede')
    # Usamos get_or_create para evitar errores si los datos ya existen
    Sede.objects.get_or_create(
        nombre='Sede Principal - Centro', 
        defaults={'direccion': 'Calle Falsa 123, Ciudad'}
    )
    Sede.objects.get_or_create(
        nombre='Sucursal Norte', 
        defaults={'direccion': 'Avenida Siempre Viva 742, Suburbio'}
    )

class Migration(migrations.Migration):

    dependencies = [
        # Asegúrate de que dependa de la migración anterior donde se creó el modelo Sede
        ('reservations', '0004_alter_reserva_fecha_hora_cita_alter_reserva_sede'), 
    ]

    operations = [
        migrations.RunPython(populate_sedes),
    ]
