# Generated by Django 5.2.6 on 2025-09-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
